version: "3.8"

services:
  aws:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:${LOCALSTACK_VERSION:-3.2.0}
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      # - ./localstack-init.sh:/etc/localstack/init/ready.d/init.sh
      - /var/run/docker.sock:/var/run/docker.sock
